# Generated by Django 5.1.1 on 2024-10-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.BooleanField(default=False, verbose_name=True),
        ),
    ]
