# Generated by Django 5.1.1 on 2024-11-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAApp', '0003_course_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
